// This file is part of Desktop App Toolkit,
// a set of libraries for developing nice desktop applications.
//
// For license and copyright information please follow this link:
// https://github.com/desktop-app/legal/blob/master/LEGAL
//
#include "codegen/lang/processor.h"

#include <QtCore/QDir>
#include <QtCore/QFileInfo>
#include <QtCore/QFile>
#include <QtCore/QTextStream>
#include <QtCore/QRegularExpression>
#include <QtCore/QSet>
#include "codegen/common/cpp_file.h"
#include "codegen/lang/parsed_file.h"
#include "codegen/lang/generator.h"

namespace codegen {
namespace lang {
namespace {

constexpr int kErrorCantWritePath = 821;

} // namespace

Processor::Processor(const Options &options)
: parser_(std::make_unique<ParsedFile>(options))
, options_(options) {
}

int Processor::launch() {
	if (!parser_->read()) {
		return -1;
	}

	if (options_.subsetsOnly) {
		return writeSubsets(parser_->getResult());
	}

	if (!write(parser_->getResult())) {
		return -1;
	}

	return 0;
}

int Processor::writeSubsets(const LangPack &langpack) const {
	if (options_.sourcesPath.isEmpty()) {
		common::logError(906, "Command Line") << "sources path required for --subsets-only";
		return -1;
	}

	QDir srcDir(options_.sourcesPath);
	if (!srcDir.exists()) {
		common::logError(907, "Command Line") << "sources path does not exist: " << options_.sourcesPath;
		return -1;
	}

	// Find all .cpp and .mm files
	QStringList filters = {"*.cpp", "*.mm"};
	QDir::Filters filtersFlags = QDir::Files | QDir::NoSymLinks;
	QDir::SortFlags sortFlags = QDir::Name;
	QStringList allFiles = srcDir.entryList(filters, filtersFlags, sortFlags);

	// Also search subdirectories
	QStringList allCppFiles;
	for (const auto &filter : filters) {
		allCppFiles.append(srcDir.entryList(QStringList() << filter, QDir::Files, QDir::Name));
	}

	// Recursively find all .cpp and .mm files
	auto findCppFiles = [&](const QDir &dir, QStringList &result) {
		QStringList subdirs = dir.entryList(QDir::Dirs | QDir::NoDotAndDotDot);
		for (const auto &subdir : subdirs) {
			QDir subdirPath = dir;
			subdirPath.cd(subdir);
			findCppFiles(subdirPath, result);
		}
		QStringList files = dir.entryList(filters, filtersFlags, sortFlags);
		for (const auto &file : files) {
			result.append(dir.absolutePath() + "/" + file);
		}
	};

	QStringList cppFiles;
	findCppFiles(srcDir, cppFiles);

	// For each file, find used tr:: keys and generate subset header
	for (const auto &filePath : cppFiles) {
		QFile file(filePath);
		if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
			continue;
		}

		QTextStream in(&file);
		QString content = in.readAll();
		file.close();

		// Find all tr::key patterns
		QRegularExpression re("tr::([a-zA-Z_][a-zA-Z0-9_]*)");
		QRegularExpressionMatchIterator i = re.globalMatch(content);
		QSet<QString> usedKeys;
		while (i.hasNext()) {
			QRegularExpressionMatch match = i.next();
			usedKeys.insert(match.captured(1));
		}

		if (usedKeys.isEmpty()) {
			continue;
		}

		// Generate subset header
		QString relativePath = srcDir.relativeFilePath(filePath);
		QString outputPath = options_.outputPath + "/lang_subsets/" + relativePath + ".h";
		QDir outputDir = QFileInfo(outputPath).absoluteDir();
		outputDir.mkpath(".");

		QFile outFile(outputPath);
		if (!outFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
			common::logError(908, "Command Line") << "cannot write to: " << outputPath;
			return -1;
		}

		QTextStream out(&outFile);
		out << "// WARNING! All changes made in this file will be lost!\n";
		out << "// Generated by codegen_lang --subsets-only\n";
		out << "#pragma once\n\n";
		out << "#include \"lang/lang_tag.h\"\n";
		out << "#include \"lang/lang_values.h\"\n\n";
		out << "namespace tr {\n";
		out << "namespace details {\n\n";
		out << "struct Identity {\n";
		out << "\tQString operator()(const QString &value) const {\n";
		out << "\t\treturn value;\n";
		out << "\t}\n";
		out << "};\n\n";
		out << "} // namespace details\n\n";
		out << "struct now_t {\n};\n\n";
		out << "inline constexpr now_t now{};\n\n";
		out << "template <typename P>\n";
		out << "using S = std::decay_t<decltype(std::declval<P>()(QString()))>;\n\n";
		out << "template <typename ...Tags>\n";
		out << "struct phrase;\n\n";

		// Find key indices for used keys
		int keyIndex = 0;
		for (const auto &entry : langpack.entries) {
			QString keyName = entry.keyBase.isEmpty() ? entry.key : entry.keyBase;
			if (usedKeys.contains(keyName)) {
				auto tags = QStringList();
				for (const auto &tagData : entry.tags) {
					tags.push_back("lngtag_" + tagData.tag);
				}
				out << "inline constexpr phrase<" << tags.join(", ") << "> " << keyName << "{ ushort(" << keyIndex << ") };\n";
			}
			++keyIndex;
		}

		out << "\n} // namespace tr\n";

		outFile.close();
	}

	return 0;
}

bool Processor::write(const LangPack &langpack) const :
	bool forceReGenerate = false;
	QDir dir(options_.outputPath);
	if (!dir.mkpath(".")) {
		common::logError(kErrorCantWritePath, "Command Line") << "can not open path for writing: " << dir.absolutePath().toStdString();
		return false;
	}

	QFileInfo srcFile(options_.inputPath);
	QString dstFilePath = dir.absolutePath() + "/lang_auto";

	common::ProjectInfo project = {
		"codegen_style",
		srcFile.fileName(),
		forceReGenerate
	};

	Generator generator(langpack, dstFilePath, project);
	if (!generator.writeHeader()
		|| !generator.writeSource()
		|| !common::TouchTimestamp(dstFilePath)) {
		return false;
	}
	return true;
}

Processor::~Processor() = default;

} // namespace lang
} // namespace codegen
